name: Build Executables

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: xpt-to-excel-windows
          - os: macos-latest
            artifact_name: xpt-to-excel-macos

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build executable (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        pyinstaller --windowed --onedir --hidden-import=pyreadstat._readstat_writer --hidden-import=pyreadstat._readstat_parser --collect-all pyreadstat --exclude-module matplotlib --exclude-module scipy --exclude-module sklearn --exclude-module pandas.tests --exclude-module torch --exclude-module numpy.tests --exclude-module IPython --exclude-module jupyter --exclude-module notebook --exclude-module tkinter --name xpt-to-excel-fast xpt_open_in_excel.py

    - name: Build executable (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        pyinstaller --windowed --onedir --hidden-import=pyreadstat._readstat_writer --hidden-import=pyreadstat._readstat_parser --collect-all pyreadstat --exclude-module matplotlib --exclude-module scipy --exclude-module sklearn --exclude-module pandas.tests --exclude-module torch --exclude-module numpy.tests --exclude-module IPython --exclude-module jupyter --exclude-module notebook --exclude-module tkinter --name xpt-to-excel-fast xpt_open_in_excel.py

    - name: Create macOS app bundle
      if: matrix.os == 'macos-latest'
      run: |
        # Create app bundle structure
        mkdir -p "XPT to Excel.app/Contents/MacOS"
        mkdir -p "XPT to Excel.app/Contents/Resources"

        # Copy executable and dependencies
        cp -r dist/xpt-to-excel-fast/* "XPT to Excel.app/Contents/MacOS/"

        # Make the main executable... executable
        chmod +x "XPT to Excel.app/Contents/MacOS/xpt-to-excel-fast"

        # Create Info.plist for file association
        cat > "XPT to Excel.app/Contents/Info.plist" << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleName</key>
            <string>XPT to Excel</string>
            <key>CFBundleDisplayName</key>
            <string>XPT to Excel Converter</string>
            <key>CFBundleIdentifier</key>
            <string>com.fda.xpt-to-excel</string>
            <key>CFBundleVersion</key>
            <string>1.0</string>
            <key>CFBundleShortVersionString</key>
            <string>1.0</string>
            <key>CFBundleExecutable</key>
            <string>xpt-to-excel-fast</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>CFBundleSignature</key>
            <string>????</string>
            <key>LSMinimumSystemVersion</key>
            <string>10.9</string>
            <key>NSHighResolutionCapable</key>
            <true/>
            <key>CFBundleDocumentTypes</key>
            <array>
                <dict>
                    <key>CFBundleTypeExtensions</key>
                    <array>
                        <string>xpt</string>
                    </array>
                    <key>CFBundleTypeName</key>
                    <string>SAS Transport File</string>
                    <key>CFBundleTypeDescription</key>
                    <string>SAS XPORT Transport File</string>
                    <key>CFBundleTypeRole</key>
                    <string>Editor</string>
                    <key>LSHandlerRank</key>
                    <string>Owner</string>
                    <key>CFBundleTypeIconFile</key>
                    <string></string>
                </dict>
            </array>
            <key>LSApplicationCategoryType</key>
            <string>public.app-category.productivity</string>
        </dict>
        </plist>
        EOF

        # Create a wrapper script to handle file arguments properly
        cat > "XPT to Excel.app/Contents/MacOS/wrapper.sh" << 'EOF'
        #!/bin/bash
        DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
        "$DIR/xpt-to-excel-fast" "$@"
        EOF

        chmod +x "XPT to Excel.app/Contents/MacOS/wrapper.sh"

        # Update Info.plist to use wrapper
        sed -i '' 's/<string>xpt-to-excel-fast<\/string>/<string>wrapper.sh<\/string>/' "XPT to Excel.app/Contents/Info.plist"

        # Create installation instructions
        cat > "macOS-Installation-Instructions.txt" << 'EOF'
        macOS Installation Instructions:
        ===============================

        1. Extract the downloaded zip file
        2. Copy "XPT to Excel.app" to your Applications folder (optional but recommended)
        3. To associate .xpt files with this app:
           - Right-click any .xpt file in Finder
           - Select "Get Info"
           - In the "Open with:" section, click the dropdown
           - Choose "Other..." and select "XPT to Excel.app"
           - Click "Change All..." to apply to all .xpt files

        4. You can now double-click .xpt files to convert them to Excel

        Note: On first run, macOS may show a security warning.
        If this happens:
        - Go to System Preferences → Security & Privacy
        - Click "Allow" next to the blocked app message
        - Or right-click the app and select "Open" to bypass the warning
        EOF

    - name: Prepare Windows distribution
      if: matrix.os == 'windows-latest'
      run: |
        # Create installation instructions for Windows
        echo "Windows Installation Instructions:" > dist/Windows-Installation-Instructions.txt
        echo "=================================" >> dist/Windows-Installation-Instructions.txt
        echo "" >> dist/Windows-Installation-Instructions.txt
        echo "1. Extract the downloaded zip file to a permanent location" >> dist/Windows-Installation-Instructions.txt
        echo "   (e.g., C:\Program Files\XPT to Excel\)" >> dist/Windows-Installation-Instructions.txt
        echo "" >> dist/Windows-Installation-Instructions.txt
        echo "2. To associate .xpt files with this converter:" >> dist/Windows-Installation-Instructions.txt
        echo "   - Right-click any .xpt file" >> dist/Windows-Installation-Instructions.txt
        echo "   - Select 'Open with' → 'Choose another app'" >> dist/Windows-Installation-Instructions.txt
        echo "   - Click 'More apps' → 'Look for another app on this PC'" >> dist/Windows-Installation-Instructions.txt
        echo "   - Browse to the extracted folder and select 'xpt-to-excel-fast.exe'" >> dist/Windows-Installation-Instructions.txt
        echo "   - Check 'Always use this app to open .xpt files'" >> dist/Windows-Installation-Instructions.txt
        echo "" >> dist/Windows-Installation-Instructions.txt
        echo "3. You can now double-click .xpt files to convert them to Excel" >> dist/Windows-Installation-Instructions.txt

    - name: Upload Windows artifact
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: |
          dist/xpt-to-excel-fast/
          dist/Windows-Installation-Instructions.txt

    - name: Upload macOS artifact
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: |
          XPT to Excel.app/
          macOS-Installation-Instructions.txt

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Windows artifact
      uses: actions/download-artifact@v4
      with:
        name: xpt-to-excel-windows
        path: ./artifacts/windows/

    - name: Download macOS artifact
      uses: actions/download-artifact@v4
      with:
        name: xpt-to-excel-macos
        path: ./artifacts/macos/

    - name: Create zip files for distributions
      run: |
        cd ./artifacts/windows && zip -r ../xpt-to-excel-windows.zip . && cd ../..
        cd ./artifacts/macos && zip -r ../xpt-to-excel-macos.zip . && cd ../..

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./artifacts/xpt-to-excel-windows.zip
          ./artifacts/xpt-to-excel-macos.zip
        body: |
          ## XPT to Excel Converter

          Convert SAS XPORT (.xpt) files to Excel format with ease.

          ### Downloads:
          - **Windows**: `xpt-to-excel-windows.zip` - Extract and follow included instructions
          - **macOS**: `xpt-to-excel-macos.zip` - Contains app bundle with installation instructions

          ### What's New:
          - Fast directory-based builds for improved performance
          - Proper macOS app bundle with file association support
          - Detailed installation instructions for both platforms

          ### Installation:
          1. Download the appropriate zip file for your operating system
          2. Extract the contents
          3. Follow the included installation instructions
          4. Associate .xpt files with the converter for easy double-click conversion
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
